# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('content_pdf', models.FileField(upload_to='')),
                ('content_text', models.TextField()),
            ],
        ),
    ]
