# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
