# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190429_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 5, 4, 18, 19, 5, 503433, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
