# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
